enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  "@subwallet/extension-base@*":
    dependencies:
      sails-js: "0.1.6"
    peerDependenciesMeta:
      sails-js:
        optional: true
