import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { KeypairType } from '@polkadot/util-crypto/types';
import { HomeScreenParams } from 'routes/home';
import { TransferNftParams } from 'stores/types';
import { ConfirmationsQueue } from '@subwallet/extension-base/background/KoniTypes';

export type RootStackParamList = {
  LockScreen: undefined;
  LoadingScreen: undefined;
  Home: HomeScreenParams | undefined;
  CreateAccount: { keyTypes: KeypairType };
  QrScanner: undefined;
  AccountsScreen: undefined;
  EditAccount: { address: string; name: string };
  RemoveAccount: { address: string };
  RestoreJson: undefined;
  ExportPrivateKey: { address: string };
  Settings: undefined;
  NetworkSelect: undefined;
  ImportSecretPhrase: { keyTypes: KeypairType };
  ImportPrivateKey: undefined;
  NetworksSetting: undefined;
  SendFund: { selectedAccount: string; selectedNetworkKey: string; selectedToken: string };
  Languages: undefined;
  Security: undefined;
  PinCode: { screen: 'NewPinCode' | 'ChangePinCode' | 'TurnoffPinCode' };
  ExportJson: undefined;
  BrowserSearch: { isOpenNewTab: boolean } | undefined;
  BrowserTabsManager: { url?: string; name?: string; isOpenTabs?: boolean };
  ConfirmationPopup: undefined;
  FavouritesGroupDetail: undefined;
  HistoryGroupDetail: undefined;
  DAppAccess: undefined;
  DAppAccessDetail: { origin: string; accountAuthType: string };
  WebViewDebugger: undefined;
  ImportEvmNft: undefined;
  TransferNft: TransferNftParams;
  EvmTokens: undefined;
  ConfigureToken: { contractAddress: string };
  ImportEvmToken: { payload: ConfirmationsQueue['addTokenRequest'][0] | undefined };
};

export type NavigationProps = NativeStackScreenProps<RootStackParamList>;
export type RootNavigationProps = NavigationProps['navigation'];
export type RootRouteProps = NavigationProps['route'];
export type CreateAccountProps = NativeStackScreenProps<RootStackParamList, 'CreateAccount'>;
export type ImportSecretPhraseProps = NativeStackScreenProps<RootStackParamList, 'ImportSecretPhrase'>;
export type PinCodeProps = NativeStackScreenProps<RootStackParamList, 'PinCode'>;
export type SendFundProps = NativeStackScreenProps<RootStackParamList, 'SendFund'>;
export type EditAccountProps = NativeStackScreenProps<RootStackParamList, 'EditAccount'>;
export type ExportPrivateKeyProps = NativeStackScreenProps<RootStackParamList, 'ExportPrivateKey'>;
export type RemoveAccountProps = NativeStackScreenProps<RootStackParamList, 'RemoveAccount'>;
export type TransferNftProps = NativeStackScreenProps<RootStackParamList, 'TransferNft'>;
export type DAppAccessDetailProps = NativeStackScreenProps<RootStackParamList, 'DAppAccessDetail'>;
export type BrowserTabsManagerProps = NativeStackScreenProps<RootStackParamList, 'BrowserTabsManager'>;
export type BrowserSearchProps = NativeStackScreenProps<RootStackParamList, 'BrowserSearch'>;
export type HomeScreenProps = NativeStackScreenProps<RootStackParamList, 'Home'>;
export type ConfigureTokenProps = NativeStackScreenProps<RootStackParamList, 'ConfigureToken'>;
export type ImportEvmTokenProps = NativeStackScreenProps<RootStackParamList, 'ImportEvmToken'>;
