import { NavigatorScreenParams } from '@react-navigation/native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { KeypairType } from '@polkadot/util-crypto/types';
import { AttachAccountStackParamList } from 'routes/account/attachAccount';
import { ImportAccountQrStackParamList } from 'routes/account/importAccountQr';
import { HomeStackParamList } from 'routes/home';
import { ConfirmationsQueue } from '@subwallet/extension-base/background/KoniTypes';
import { ClaimStakeActionStackParamList } from 'routes/staking/claimAction';
import { CompoundStakeActionStackParamList } from 'routes/staking/compoundAction';
import { StakeActionStackParamList } from 'routes/staking/stakeAction';
import { UnStakeActionStackParamList } from 'routes/staking/unStakeAction';
import { WithdrawStakeActionStackParamList } from 'routes/staking/withdrawAction';
import { TransferNftParams } from 'types/nft';

export type RootStackParamList = {
  LockScreen: undefined;
  LoadingScreen: undefined;
  Home: NavigatorScreenParams<HomeStackParamList> | undefined;
  CreateAccount: { keyTypes: KeypairType };
  QrScanner: undefined;
  AccountsScreen: undefined;
  EditAccount: { address: string; name: string };
  RemoveAccount: { address: string };
  RestoreJson: undefined;
  ExportPrivateKey: { address: string };
  Settings: undefined;
  NetworkSelect: undefined;
  ImportSecretPhrase: { keyTypes: KeypairType };
  ImportPrivateKey: undefined;
  NetworksSetting: undefined;
  SendFund: { selectedNetworkKey?: string; selectedToken?: string };
  Languages: undefined;
  Security: undefined;
  PinCode: { screen: 'NewPinCode' | 'ChangePinCode' | 'TurnoffPinCode' };
  ExportAccount: { address: string; exportType: 'json' | 'privateKey' };
  ExportJson: { address: string };
  BrowserSearch: { isOpenNewTab: boolean } | undefined;
  BrowserTabsManager: { url?: string; name?: string; isOpenTabs?: boolean };
  ConfirmationPopup: undefined;
  FavouritesGroupDetail: undefined;
  HistoryGroupDetail: undefined;
  DAppAccess: undefined;
  DAppAccessDetail: { origin: string; accountAuthType: string };
  WebViewDebugger: undefined;
  ImportEvmNft: { payload: ConfirmationsQueue['addTokenRequest'][0] | undefined };
  TransferNft: TransferNftParams;
  EvmTokens: undefined;
  ConfigureToken: { contractAddress: string };
  ImportEvmToken: { payload: ConfirmationsQueue['addTokenRequest'][0] | undefined };
  StakeAction: NavigatorScreenParams<StakeActionStackParamList>;
  UnStakeAction: NavigatorScreenParams<UnStakeActionStackParamList>;
  WithdrawStakeAction: NavigatorScreenParams<WithdrawStakeActionStackParamList>;
  ClaimStakeAction: NavigatorScreenParams<ClaimStakeActionStackParamList>;
  CompoundStakeAction: NavigatorScreenParams<CompoundStakeActionStackParamList>;
  NetworkConfig: undefined;
  NetworkConfigDetail: { key: string };
  AttachAccount: NavigatorScreenParams<AttachAccountStackParamList>;
};

export type NavigationProps = NativeStackScreenProps<RootStackParamList>;
export type RootNavigationProps = NavigationProps['navigation'];
export type RootRouteProps = NavigationProps['route'];
export type CreateAccountProps = NativeStackScreenProps<RootStackParamList, 'CreateAccount'>;
export type ImportSecretPhraseProps = NativeStackScreenProps<RootStackParamList, 'ImportSecretPhrase'>;
export type PinCodeProps = NativeStackScreenProps<RootStackParamList, 'PinCode'>;
export type SendFundProps = NativeStackScreenProps<RootStackParamList, 'SendFund'>;
export type EditAccountProps = NativeStackScreenProps<RootStackParamList, 'EditAccount'>;
export type ExportPrivateKeyProps = NativeStackScreenProps<RootStackParamList, 'ExportPrivateKey'>;
export type ExportAccountProps = NativeStackScreenProps<RootStackParamList, 'ExportAccount'>;
export type ExportJsonProps = NativeStackScreenProps<RootStackParamList, 'ExportJson'>;
export type RemoveAccountProps = NativeStackScreenProps<RootStackParamList, 'RemoveAccount'>;
export type TransferNftProps = NativeStackScreenProps<RootStackParamList, 'TransferNft'>;
export type DAppAccessDetailProps = NativeStackScreenProps<RootStackParamList, 'DAppAccessDetail'>;
export type BrowserTabsManagerProps = NativeStackScreenProps<RootStackParamList, 'BrowserTabsManager'>;
export type BrowserSearchProps = NativeStackScreenProps<RootStackParamList, 'BrowserSearch'>;
export type HomeScreenProps = NativeStackScreenProps<RootStackParamList, 'Home'>;
export type ConfigureTokenProps = NativeStackScreenProps<RootStackParamList, 'ConfigureToken'>;
export type ImportEvmTokenProps = NativeStackScreenProps<RootStackParamList, 'ImportEvmToken'>;
export type StakeActionProps = NativeStackScreenProps<RootStackParamList, 'StakeAction'>;
export type UnStakeAction = NativeStackScreenProps<RootStackParamList, 'UnStakeAction'>;
export type NetworkConfigDetailProps = NativeStackScreenProps<RootStackParamList, 'NetworkConfigDetail'>;
