// Credit: https://github.com/nova-wallet/nova-utils/blob/master/dapps/dapps_dev.json

import { PredefinedDApps } from 'types/browser';

export const predefinedDApps: PredefinedDApps = {
  categories: [
    {
      name: 'DeFi',
      id: 'defi',
    },
    {
      name: 'NFT',
      id: 'nft',
    },
    {
      name: 'EVM',
      id: 'evm',
    },
    {
      name: 'Community',
      id: 'community',
    },
    {
      name: 'Utilities',
      id: 'utilities',
    },
    {
      name: 'Crowdloans',
      id: 'crowdloans',
    },
    {
      name: 'Staking',
      id: 'staking',
    },
    {
      name: 'Test',
      id: 'test',
    },
  ],
  dapps: [
    {
      name: 'Singular 2.0',
      url: 'https://singular.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular_2.0.svg',
      categories: ['nft'],
    },
    {
      name: 'Singular',
      url: 'https://singular.rmrk.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular.svg',
      categories: ['nft'],
    },
    {
      name: 'Kanaria',
      url: 'https://kanaria.rmrk.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Kanaria.svg',
      categories: ['nft'],
    },
    {
      name: 'Bifrost App',
      url: 'https://bifrost.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Bifrost.svg',
      categories: ['defi', 'crowdloans'],
    },
    {
      name: 'Astar DApp Hub',
      url: 'https://portal.astar.network/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Astar.png',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'Subsocial App',
      url: 'https://app.subsocial.network/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Subsocial.png',
      categories: ['community'],
    },
    // {
    //   name: 'Sub.ID',
    //   url: 'https://sub.id/#/',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Sub.ID.png',
    //   categories: ['utilities'],
    // },
    {
      name: 'Polkadot.js',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkadot.js.svg',
      url: 'https://polkadot.js.org/apps/#',
      categories: ['utilities'],
    },
    {
      name: 'KodaDot',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/KodaDot.png',
      url: 'https://kodadot.xyz/',
      categories: ['nft'],
    },
    {
      name: 'Dotmarketcap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Dotmarketcap.svg',
      url: 'https://dotmarketcap.com/',
      categories: ['utilities'],
    },
    {
      name: 'Parallel Finance App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Parallel-Heiko.svg',
      url: 'https://app.parallel.fi/',
      categories: ['defi'],
    },
    {
      name: 'Polkassembly',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkassembly.svg',
      url: 'https://polkadot.polkassembly.io/',
      categories: ['community'],
    },
    // {
    //   name: 'Talisman App',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Talisman.svg',
    //   url: 'https://app.talisman.xyz/portfolio',
    //   categories: ['defi', 'crowdloans'],
    // },
    // {
    //   name: 'Phala App',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Phala.svg',
    //   url: 'https://app.phala.network/',
    //   categories: ['defi', 'staking'],
    // },
    {
      name: 'Bit.Country Pioneer Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Bit.Country.svg',
      url: 'https://ksmcrowdloan.bit.country/reward',
      categories: ['crowdloans'],
    },
    {
      name: 'Parallel Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Parallel-Heiko.svg',
      url: 'https://crowdloan.parallel.fi/',
      categories: ['crowdloans'],
    },
    {
      name: 'Kintsugi Hub',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Kintsugi.svg',
      url: 'https://kintsugi.interlay.io/',
      categories: ['staking', 'defi', 'crowdloans'],
    },
    // {
    //   name: 'Altair Rewards Claim',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Altair.svg',
    //   url: 'https://centrifuge.io/altair/crowdloan/',
    //   categories: ['crowdloans'],
    // },
    // {
    //   name: 'Clover Rewards Claim',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Clover.svg',
    //   url: 'https://lucky.clover.finance/',
    //   categories: ['crowdloans'],
    // },
    // {
    //   name: 'Karura App (not mobile-friendly yet)',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Karura.svg',
    //   url: 'https://apps.karura.network/',
    //   categories: ['defi', 'staking', 'community'],
    // },
    // {
    //   name: 'KILT Stakeboard (not mobile-friendly yet)',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/KILT.svg',
    //   url: 'https://stakeboard.kilt.io/',
    //   categories: ['staking'],
    // },
    // {
    //   name: 'Subsquare. Khala network',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/SubSquare.svg',
    //   url: 'https://khala.subsquare.io/',
    //   categories: ['community'],
    // },
    // {
    //   name: 'Subsquare',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/SubSquare.svg',
    //   url: 'https://polkadot.subsquare.io/',
    //   categories: ['community'],
    // },
    {
      name: 'Acala Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Acala.png',
      url: 'https://distribution.acala.network/claim/acala',
      categories: ['crowdloans'],
    },
    {
      name: 'Robonomics',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Robonomics.svg',
      url: 'https://dapp.robonomics.network/#/staking/',
      categories: ['staking'],
    },
    {
      name: 'Moonbeam',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonbeam.svg',
      url: 'https://apps.moonbeam.network/moonbeam',
      categories: ['staking', 'crowdloans', 'evm'],
    },
    {
      name: 'Moonriver',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonriver.svg',
      url: 'https://apps.moonbeam.network/moonriver',
      categories: ['staking', 'crowdloans', 'evm'],
    },
    {
      name: 'Solarflare',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Solarflare.png',
      url: 'https://app.solarflare.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'Solarbeam',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Solarbeam.png',
      url: 'https://app.solarbeam.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'Beamswap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Beamswap.svg',
      url: 'https://app.beamswap.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'Stellaswap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/StellaSwap.svg',
      url: 'https://app.stellaswap.com/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'Impossible Finance',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ImpossibleFinance.svg',
      url: 'https://app.impossible.finance/explore',
      categories: ['defi', 'evm'],
    },
    {
      name: 'Huckleberry Finance',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Huckleberry.svg',
      url: 'https://www.huckleberry.finance/#/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    // {
    //   name: 'MyTrade',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/MyTrade.svg',
    //   url: 'https://mytrade.org/',
    //   categories: ['defi', 'evm'],
    // },
    // {
    //   name: 'Kintsugi TESTNET',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Kintsugi.svg',
    //   url: 'https://bridge.interlay.io/bridge?tab=issue',
    //   categories: ['test'],
    // },
    {
      name: 'Singular',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular_2.0.svg',
      url: 'https://singular-rmrk2-dev.vercel.app/',
      categories: ['test'],
    },
    {
      name: 'Centrifuge Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Centrifuge.svg',
      url: 'https://centrifuge.io/parachain/crowdloan/',
      categories: ['crowdloans'],
    },
    {
      name: 'DappRadar',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/DappRadar.svg',
      url: 'https://dappradar.com/',
      categories: ['utilities'],
    },
    // {
    //   name: 'PolkaEx',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/PolkaEx.svg',
    //   url: 'https://app.polkaex.io/swap',
    //   categories: ['defi', 'staking', 'evm'],
    // },
    {
      name: 'TofuNFT',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/TofuNFT.svg',
      url: 'https://tofunft.com/',
      categories: ['nft', 'evm'],
    },
    // {
    //   name: '1Beam',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/1beam.png',
    //   url: 'https://1beam.io/',
    //   categories: ['defi', 'staking', 'evm'],
    // },
    {
      name: 'ArthSwap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ArthSwap.svg',
      url: 'https://app.arthswap.org/#/swap',
      categories: ['defi', 'staking', 'evm'],
    },
    {
      name: 'cBRIDGE',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/cBRIDGE.png',
      url: 'https://cbridge.celer.network/#/transfer',
      categories: ['defi', 'evm'],
    },
    {
      name: 'XDAO',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/XDAO.svg',
      url: 'https://www.xdao.app/137',
      categories: ['defi', 'evm'],
    },
    // {
    //   name: 'SiriusFinance',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/SiriusFinance.svg',
    //   url: 'https://app.sirius.finance/#/swap',
    //   categories: ['defi', 'staking', 'evm'],
    // },
    {
      name: 'Interlay Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Interlay.svg',
      url: 'https://crowdloan.interlay.io/',
      categories: ['crowdloans'],
    },
    {
      name: 'Kusama Lido',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_KSM.svg',
      url: 'https://kusama.lido.fi/',
      categories: ['staking', 'evm'],
    },
    {
      name: 'Polkadot Lido',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_DOT.svg',
      url: 'https://polkadot.lido.fi/',
      categories: ['staking', 'evm'],
    },
    {
      name: 'Moonwell Apollo',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonwell.svg',
      url: 'https://moonwell.fi/apollo/MOVR',
      categories: ['defi', 'evm'],
    },
    {
      name: 'Litmus App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Litmus-original.svg',
      url: 'https://apps.litentry.com/',
      categories: ['crowdloans', 'evm'],
    },
    {
      name: 'Darwinia App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Darwinia.svg',
      url: 'https://apps.darwinia.network/',
      categories: ['staking'],
    },
    // {
    //   name: 'SubBridge',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/SubBridge.svg',
    //   url: 'https://subbridge.io/',
    //   categories: ['defi', 'evm'],
    // },
    {
      name: 'Moonwell Artemis',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/MoonwellArtemis.svg',
      url: 'https://moonwell.fi/artemis/GLMR',
      categories: ['defi', 'evm'],
    },
    // {
    //   name: 'Skybreach',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Skybreach.png',
    //   url: 'https://skybreach.app/',
    //   categories: ['nft', 'evm'],
    // },
    {
      name: 'Polkawatch',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkawatch.svg',
      url: 'https://polkawatch.app/',
      categories: ['staking'],
    },
    {
      name: 'Damned Pirates Society',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Damnedpiratessociety.svg',
      url: 'https://damnedpiratessociety.io/',
      categories: ['nft', 'evm'],
    },
    {
      name: 'Polkadot Staking Dashboard',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/StakingDashboard.svg',
      url: 'https://staking.polkadot.network/dashboard#/overview',
      categories: ['staking'],
    },
    {
      name: 'Moonsama',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonsama.svg',
      url: 'https://marketplace.moonsama.com/',
      categories: ['nft', 'evm'],
    },
    {
      name: 'EVRLOOT',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/EVRLOOT.svg',
      url: 'https://game.evrloot.com/game',
      categories: ['nft'],
    },
    {
      name: 'Downtown Moonbeam',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/DowntownMoonbeam.png',
      url: 'https://dtmb.xyz',
      categories: ['evm', 'utilities'],
    },
    {
      name: 'Evolution Land. Columbus',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Evolutionland.png',
      url: 'https://portal.evolution.land/land/3/market/land',
      categories: ['nft', 'evm'],
    },
    {
      name: 'Basilisk Snek Swap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/SnekSwap.svg',
      url: 'https://app.basilisk.cloud/#/trade',
      categories: ['defi'],
    },
    {
      name: 'Moonbeam Curve',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/MoonbeamCurve.svg',
      url: 'https://moonbeam.curve.fi/',
      categories: ['defi', 'evm'],
    },
    // {
    //   name: 'Nomad',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Nomad.svg',
    //   url: 'https://app.nomad.xyz/',
    //   categories: ['defi', 'evm'],
    // },
    {
      name: 'GM! Say it back',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/GM.svg',
      url: 'https://app.gmordie.com/',
      categories: ['community'],
    },
    // {
    //   name: 'Tinkernet Rewards Claim',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Tinkernet.svg',
    //   url: 'https://www.tinker.network/claim',
    //   categories: ['crowdloans'],
    // },
    // {
    //   name: 'Raresama',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Raresama.svg',
    //   url: 'https://raresama.com/',
    //   categories: ['nft'],
    // },
    {
      name: 'Bit.Country Pioneer Metaverse',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Bit.Country.svg',
      url: 'https://pioneer.bit.country/',
      categories: ['nft', 'staking'],
    },
    {
      name: 'Zeitgeist',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Zeitgeist.svg',
      url: 'https://app.zeitgeist.pm/',
      categories: ['nft', 'utilities'],
    },
    {
      name: 'ACE',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ACE.svg',
      url: 'https://ace.web3go.xyz/#/',
      categories: ['utilities'],
    },
    {
      name: 'Subwallet connect',
      icon: 'https://connect.subwallet.app/icon-128.png',
      url: 'https://connect.subwallet.app/',
      categories: ['test'],
    },
  ],
};
