// Credit: https://github.com/nova-wallet/nova-utils/blob/master/dapps/dapps_dev.json

import { PredefinedDApps } from 'types/browser';

export const DAppIconMap: Record<string, string> = {
  'kintsugi.interlay.io': 'https://kintsugi.interlay.io/kintsugi/apple-touch-icon.png',
  'kanaria.rmrk.app': 'https://rmrk-unrestricted.mypinata.cloud/ipfs/QmSkVkPiMsr1Ryu7122KHoAHqsCrgQCWthNniykLKqbA5H',
  'distribution.acala.network': 'https://avatars.githubusercontent.com/u/54881907?s=200&v=4',
  'www.xdao.app': 'https://moonbeam.network/wp-content/uploads/2022/03/xDAO.png',
  'crowdloan.interlay.io': 'https://assets.coingecko.com/coins/images/26180/small/Interlay-Coinbase-2.png',
  'ace.web3go.xyz': 'https://ace.web3go.xyz/favicon.ico',
  'www.avault.network': 'https://www.avault.network/logo.png',
  'astr.domains': 'https://astr.domains/logo/logo_cic.png',
  'tfalpha.xyz': 'https://tfalpha.xyz/img/tfa-logo.png',
};

export const DAppTitleMap: Record<string, string> = {
  'singular.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'singular.rmrk.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'kanaria.rmrk.app': 'KANARIA',
  'bifrost.app': 'Bifrost',
  'portal.astar.network': 'Astar Portal - Astar & Shiden Network',
  'app.subsocial.network': 'Subsocial - Decentralized social network on Polkadot & IPFS',
  'polkadot.js.org': 'Polkadot/Substrate Portal',
  'kodadot.xyz': 'KodaDot - Kusama NFT Market Explorer',
  'dotmarketcap.com': 'DotMarketCap',
  'app.parallel.fi': 'Parallel Finance',
  'polkadot.polkassembly.io': 'Polkassembly',
  'ksmcrowdloan.bit.country': 'Crowdloan - Bit.Country Pioneer Network',
  'crowdloan.parallel.fi': 'Parallel Finance',
  'kintsugi.interlay.io': 'Kintsugi',
  'distribution.acala.network': 'Acala Distribution Query',
  'dapp.robonomics.network': 'Dapp Robonomics network',
  'apps.moonbeam.network': 'Moonbeam Network Apps',
  'app.solarflare.io': 'Solarflare',
  'app.solarbeam.io': 'Solarbeam',
  'app.beamswap.io': 'Beamswap',
  'app.stellaswap.com': 'StellaSwap - Leading Moonbeam DEX & DeFi Gateway',
  'app.impossible.finance': 'Impossible Finance',
  'clover.huckleberry.finance': 'Huckleberry',
  'moonriver.huckleberry.finance': 'moonriver.huckleberry.finance',
  'singular-rmrk2-dev.vercel.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'centrifuge.io': 'Centrifuge: Real World DeFi',
  'dappradar.com': 'DappRadar - The World’s Dapp Store',
  'tofunft.com': 'tofuNFT.com',
  'app.arthswap.org': 'ArthSwap',
  'cbridge.celer.network': 'cBridge',
  'www.xdao.app': 'XDAO – MultiChain DAO Ecosystem',
  'crowdloan.interlay.io': 'Interlay',
  'kusama.lido.fi': 'Lido',
  'polkadot.lido.fi': 'Lido',
  'moonwell.fi': 'Moonwell Apollo',
  'apps.litentry.com': 'Litmus Network',
  'apps.darwinia.network': 'Darwinia',
  'polkawatch.app': 'Polkawatch',
  'damnedpiratessociety.io': 'Damned Pirates Society',
  'staking.polkadot.network': 'Polkadot Staking Dashboard',
  'marketplace.moonsama.com': 'Moonsama',
  'game.evrloot.com': 'Join the Adventure -- evrloot',
  'www.dtmb.xyz': 'DOWNTOWN MOONBEAM',
  'portal.evolution.land': 'Evolution Land',
  'app.basilisk.cloud': 'Basilisk',
  'moonbeam.curve.fi': 'Curve.fi',
  'app.gmordie.com': 'GM - Say it back!',
  'pioneer.bit.country': 'Bit Country - Metaverses made of 1 and 0 bits',
  'app.zeitgeist.pm': 'The Zeitgeist Prediction Markets App',
  'ace.web3go.xyz': 'ACE',
  'mf-raffle-game.web.app': 'Moonfit - Raffle game',
  'dev-event.moonfit.xyz': 'Moonfit - Raffle game',
  'connect.subwallet.app': 'SubWallet Connect',
  'www.dotinsights.xyz': 'dotinsights | Polkadot & Kusama Ecosystem Map',
  'dotinsights.subwallet.app': 'dotinsights | Polkadot & Kusama Ecosystem Map',
  'app.phala.network': 'Phala App',
  'dex.zenlink.pro': 'Zenlink',
  'www.avault.network': 'Avault',
  'panoramaswap.app': 'Panorama Swap',
  'app.taigaprotocol.io': 'TAIGA',
  'astr.domains': 'Astar Web3 Domains (.astr) - Your Perfect NFT Domains',
  'event.tfalpha.xyz': 'Raffle & Claim Rewards',
  'tfalpha.xyz': 'Utopia & TF Alpha',
  'moons.money': 'Moon Web3 identity',
  'www.subsquare.io': 'SubSquare - Empower the governance of substrate.',
  'mint.azeropunks.com': 'AzeroPunks',
  'app.polkasafe.xyz': 'Polkasafe',
  'www.bananaswap.app': 'Bananaswap',
  'app.bounce.finance': 'Bounce',
  'www.hashkey.id': 'Bounce',
  'bluez.app': 'Bluez',
  'enterthemandala.app': 'Mandala',
  'www.mangata.finance': 'Mangata - The DEX of the future',
  'app.dam.finance': 'DAM',
  'apps.acala.network': 'Acala Platform',
  'app.equilibrium.io': 'Equilibrium',
  'www.gear-tech.io': 'Gear Technologies | Crypto. Smarter.',
  'apps.karura.network': 'Karura Platform',
  'app.moonfit.xyz': 'MoonFit - Web3 & NFT Lifestyle App',
  'app.sirius.finance': 'Sirius Finance',
  'sub.id': 'Sub ID: Substrate Addresses, Balances, Crowdloans and NFTs',
  'polkaverse.com': "PolkaVerse – Polkadot's Premier Social Network",
  'polkaswap.io': 'Swap - Polkaswap',
  'app.privadex.xyz': 'PrivaDEX',
  'notifi.network': 'Notifi',
  'skybreach.app': 'Kanaria Skybreach',
  'pods.spacers.app': 'Spacers NFT Pods Sale',
  'list.yieldbay.io': 'YieldBay',
  'app.fidi.tech': 'FiDi',
  'www.braindex.io': 'Braindex | Smart Dex Aggregator',
  'app.uniswap.org': 'Swap - Curve',
  'curve.fi': 'Aave - Open Source Liquidity Protocol',
  'app.aave.com': 'Aave - Open Source Liquidity Protocol',
  'lido.fi': 'Liquid Staking for Digital Tokens',
  'blur.io': 'Blur: NFT Marketplace for Pro Traders',
  'app.1inch.io': '1inch - DeFi / DEX aggregator on Ethereum, Binance Smart Chain, Optimism, Polygon, Arbitrum',
  'chainlist.org': 'Chainlist',
  'app.multichain.org': 'Multichain - Cross Chain Router Protocol',
  'www.portalbridge.com': 'Wormhole Bridge',
  'verse.bitcoin.com': 'Verse DEX',
};

export const predefinedDApps: PredefinedDApps = {
  categories: [
    {
      name: 'DeFi',
      id: 'defi',
    },
    {
      name: 'NFT',
      id: 'nft',
    },
    {
      name: 'EVM',
      id: 'evm',
    },
    {
      name: 'Community',
      id: 'community',
    },
    {
      name: 'Utilities',
      id: 'utilities',
    },
    {
      name: 'Crowdloans',
      id: 'crowdloans',
    },
    {
      name: 'Staking',
      id: 'staking',
    },
    {
      name: 'Test',
      id: 'test',
    },
    {
      name: 'Data',
      id: 'data',
    },
  ],
  dapps: [
    {
      name: 'ArtZero.io - NFT Marketplace for Astar Network Blockchain',
      icon: 'https://astar.artzero.io/assets/favicon/favicon-32x32.png',
      id: 'astar.artzero.io',
      url: 'https://astar.artzero.io/',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Subwallet connect',
      icon: 'https://connect.subwallet.app/icon-128.png',
      id: 'connect.subwallet.app',
      url: 'https://connect.subwallet.app/#/',
      categories: ['test'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'dotinsights | Polkadot & Kusama Ecosystem Map',
      id: 'www.dotinsights.xyz',
      url: 'https://www.dotinsights.xyz',
      icon: 'https://dotinsights.subwallet.app/assets/images/favicon/favicon-180x180.png',
      categories: ['data', 'utilities'],
      // isSupportSubstrateAccount: true,
    },
    {
      name: 'dotinsights | Polkadot & Kusama Ecosystem Map',
      id: 'dotinsights.subwallet.app',
      url: 'https://dotinsights.subwallet.app/',
      icon: 'https://dotinsights.subwallet.app/assets/images/favicon/favicon-180x180.png',
      categories: ['data', 'utilities'],
      // isSupportSubstrateAccount: true,
    },
    {
      name: 'Singular 2.0',
      id: 'singular.app',
      url: 'https://singular.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular_2.0.svg',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Singular',
      id: 'singular.rmrk.app',
      url: 'https://singular.rmrk.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular.svg',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Kanaria',
      id: 'kanaria.rmrk.app',
      url: 'https://kanaria.rmrk.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Kanaria.svg',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Bifrost App',
      id: 'bifrost.app',
      url: 'https://bifrost.app/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Bifrost.svg',
      categories: ['defi', 'crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Astar DApp Hub',
      id: 'portal.astar.network',
      url: 'https://portal.astar.network/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Astar.png',
      categories: ['defi', 'staking', 'evm'],
      // isSupportSubstrateAccount: true,
      // isSupportEthereumAccount: true,
    },
    {
      name: 'Subsocial App',
      id: 'app.subsocial.network',
      url: 'https://app.subsocial.network/',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Subsocial.png',
      categories: ['community'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Polkadot.js',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkadot.js.svg',
      id: 'polkadot.js.org/apps',
      url: 'https://polkadot.js.org/apps/#',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'KodaDot',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/KodaDot.png',
      id: 'kodadot.xyz',
      url: 'https://kodadot.xyz/',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Dotmarketcap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Dotmarketcap.svg',
      id: 'dotmarketcap.com',
      url: 'https://dotmarketcap.com/',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Parallel Finance App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Parallel-Heiko.svg',
      id: 'app.parallel.fi',
      url: 'https://app.parallel.fi/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Polkassembly',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkassembly.svg',
      id: 'polkadot.polkassembly.io',
      url: 'https://polkadot.polkassembly.io/',
      categories: ['community'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Astar Web3 Domains',
      icon: 'https://astr.domains/logo/logo_cic.png',
      id: 'astr.domains/buy',
      url: 'https://astr.domains/buy',
      categories: ['community'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Utopia & TF Alpha',
      icon: 'https://tfalpha.xyz/img/tfa-logo.png',
      id: 'tfalpha.xyz',
      url: 'https://tfalpha.xyz/',
      categories: ['community'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Raffle & Claim Rewards',
      icon: 'https://event.tfalpha.xyz/logo-32x32.ico',
      id: 'event.tfalpha.xyz',
      url: 'https://event.tfalpha.xyz/',
      categories: ['community'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Phala App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Phala.svg',
      id: 'app.phala.network',
      url: 'https://app.phala.network/',
      categories: ['defi', 'staking'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Bit.Country Pioneer Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Bit.Country.svg',
      id: 'ksmcrowdloan.bit.country/reward',
      url: 'https://ksmcrowdloan.bit.country/reward',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Parallel Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Parallel-Heiko.svg',
      id: 'crowdloan.parallel.fi',
      url: 'https://crowdloan.parallel.fi/',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Kintsugi Hub',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Kintsugi.svg',
      id: 'kintsugi.interlay.io',
      url: 'https://kintsugi.interlay.io/',
      categories: ['staking', 'defi', 'crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Subsquare',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/SubSquare.svg',
      id: 'www.subsquare.io',
      url: 'https://www.subsquare.io/',
      categories: ['community'],
    },
    {
      name: 'Acala Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Acala.png',
      id: 'distribution.acala.network/claim/acala',
      url: 'https://distribution.acala.network/claim/acala',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Robonomics',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Robonomics.svg',
      id: 'dapp.robonomics.network/#/staking',
      url: 'https://dapp.robonomics.network/#/staking/',
      categories: ['staking'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Moonbeam',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonbeam.svg',
      id: 'apps.moonbeam.network/moonbeam',
      url: 'https://apps.moonbeam.network/moonbeam',
      categories: ['staking', 'crowdloans', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moonriver',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonriver.svg',
      id: 'apps.moonbeam.network/moonriver',
      url: 'https://apps.moonbeam.network/moonriver',
      categories: ['staking', 'crowdloans', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Solarflare',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Solarflare.png',
      id: 'app.solarflare.io/exchange/swap',
      url: 'https://app.solarflare.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Solarbeam',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Solarbeam.png',
      id: 'app.solarbeam.io/exchange/swap',
      url: 'https://app.solarbeam.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Beamswap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Beamswap.svg',
      id: 'app.beamswap.io/exchange/swap',
      url: 'https://app.beamswap.io/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Stellaswap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/StellaSwap.svg',
      id: 'app.stellaswap.com/exchange/swap',
      url: 'https://app.stellaswap.com/exchange/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moon Web3 identity',
      icon: 'https://moons.money/logo/logo.png?=2',
      id: 'moons.money/app',
      url: 'https://moons.money/app',
      categories: ['evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Impossible Finance',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ImpossibleFinance.svg',
      id: 'app.impossible.finance/explore',
      url: 'https://app.impossible.finance/explore',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Huckleberry Finance',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Huckleberry.svg',
      id: 'clover.huckleberry.finance/#/swap',
      url: 'https://clover.huckleberry.finance/#/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Huckleberry Finance',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Huckleberry.svg',
      id: 'moonriver.huckleberry.finance/#/swap',
      url: 'https://moonriver.huckleberry.finance/#/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Singular',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Singular_2.0.svg',
      id: 'singular-rmrk2-dev.vercel.app',
      url: 'https://singular-rmrk2-dev.vercel.app/',
      categories: ['test'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Centrifuge Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Centrifuge.svg',
      id: 'centrifuge.io/parachain/crowdloan',
      url: 'https://centrifuge.io/parachain/crowdloan/',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'DappRadar',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/DappRadar.svg',
      id: 'dappradar.com',
      url: 'https://dappradar.com/',
      categories: ['utilities'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'TofuNFT',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/TofuNFT.svg',
      id: 'tofunft.com',
      url: 'https://tofunft.com/',
      categories: ['nft', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'ArthSwap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ArthSwap.svg',
      id: 'app.arthswap.org/#/swap',
      url: 'https://app.arthswap.org/#/swap',
      categories: ['defi', 'staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'The Best Crypto & Binance Bridge | cBridge',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/cBRIDGE.png',
      id: 'cbridge.celer.network/#/transfer',
      url: 'https://cbridge.celer.network/#/transfer',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'XDAO',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/XDAO.svg',
      id: 'www.xdao.app/137',
      url: 'https://www.xdao.app/137',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Interlay Rewards Claim',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Interlay.svg',
      id: 'crowdloan.interlay.io',
      url: 'https://crowdloan.interlay.io/',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Kusama Lido',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_KSM.svg',
      id: 'kusama.lido.fi',
      url: 'https://kusama.lido.fi/',
      categories: ['staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Polkadot Lido',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_DOT.svg',
      id: 'polkadot.lido.fi',
      url: 'https://polkadot.lido.fi/',
      categories: ['staking', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moonwell Apollo',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonwell.svg',
      id: 'moonwell.fi/apollo/MOVR',
      url: 'https://moonwell.fi/apollo/MOVR',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Litmus App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/Litmus-original.svg',
      id: 'apps.litentry.com',
      url: 'https://apps.litentry.com/',
      categories: ['crowdloans'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Darwinia App',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Darwinia.svg',
      id: 'apps.darwinia.network',
      url: 'https://apps.darwinia.network/',
      categories: ['staking'],
    },
    {
      name: 'Moonwell Artemis',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/MoonwellArtemis.svg',
      id: 'moonwell.fi/artemis/GLMR',
      url: 'https://moonwell.fi/artemis/GLMR',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Polkawatch',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Polkawatch.svg',
      id: 'polkawatch.app',
      url: 'https://polkawatch.app/',
      categories: ['staking'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Damned Pirates Society',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Damnedpiratessociety.svg',
      id: 'damnedpiratessociety.io',
      url: 'https://damnedpiratessociety.io/',
      categories: ['nft', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Polkadot Staking Dashboard',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/StakingDashboard.svg',
      id: 'staking.polkadot.network/dashboard#/overview',
      url: 'https://staking.polkadot.network/dashboard#/overview',
      categories: ['staking'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Moonsama',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonsama.svg',
      id: 'marketplace.moonsama.com',
      url: 'https://marketplace.moonsama.com/',
      categories: ['nft', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'EVRLOOT',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/EVRLOOT.svg',
      id: 'game.evrloot.com/game',
      url: 'https://game.evrloot.com/game',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Evolution Land. Columbus',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Evolutionland.png',
      id: 'portal.evolution.land/land/3/market/land',
      url: 'https://portal.evolution.land/land/3/market/land',
      categories: ['nft', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Basilisk Snek Swap',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/SnekSwap.svg',
      id: 'app.basilisk.cloud/#/trade',
      url: 'https://app.basilisk.cloud/#/trade',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Moonbeam Curve',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/MoonbeamCurve.svg',
      id: 'moonbeam.curve.fi',
      url: 'https://moonbeam.curve.fi/',
      categories: ['defi', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'GM! Say it back',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/GM.svg',
      id: 'app.gmordie.com',
      url: 'https://app.gmordie.com/',
      categories: ['community'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Bit.Country Pioneer Metaverse',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Bit.Country.svg',
      id: 'pioneer.bit.country',
      url: 'https://pioneer.bit.country/',
      categories: ['nft', 'staking'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Zenlink',
      icon: 'https://dex.zenlink.pro/favicon.png',
      id: 'dex.zenlink.pro/#/swap',
      url: 'https://dex.zenlink.pro/#/swap',
      categories: ['defi'],
    },
    {
      name: 'Avault',
      icon: 'https://www.avault.network/logo.png',
      id: 'www.avault.network/vault',
      url: 'https://www.avault.network/vault',
      categories: ['evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Panorama Swap',
      icon: 'https://panoramaswap.app/favicon.ico',
      id: 'panoramaswap.app',
      url: 'https://panoramaswap.app/',
      categories: ['defi'],
    },
    {
      name: 'TAIGA',
      icon: 'https://d1fdloi71mui9q.cloudfront.net/8c4qoYY4S6mBVV2NUyYQ_Jq4cFVrgwJ9EF784',
      id: 'app.taigaprotocol.io/assets',
      url: 'https://app.taigaprotocol.io/assets',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Zeitgeist',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/white/Zeitgeist.svg',
      id: 'app.zeitgeist.pm',
      url: 'https://app.zeitgeist.pm/',
      categories: ['nft', 'utilities'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'ACE',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/ACE.svg',
      id: 'ace.web3go.xyz/#',
      url: 'https://ace.web3go.xyz/#/',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Moonfit - Raffle game',
      icon: 'https://dev-event.moonfit.xyz/logo-32x32.ico',
      id: 'mf-raffle-game.web.app',
      url: 'https://mf-raffle-game.web.app',
      categories: ['evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moonfit - Raffle game',
      icon: 'https://dev-event.moonfit.xyz/logo-32x32.ico',
      id: 'dev-event.moonfit.xyz',
      url: 'https://dev-event.moonfit.xyz',
      categories: ['test', 'evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: "HydraDX - Polkadot's Multi-Headed Liquidity Monster",
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Hydradx.svg',
      id: 'hydradx.io',
      url: 'https://hydradx.io',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Cask',
      icon: 'https://app.cask.fi/favicon.ico',
      id: 'app.cask.fi',
      url: 'https://app.cask.fi',
      categories: ['evm'],
      isSupportEthereumAccount: true,
    },
    {
      name: 'Secret Stash - Ternoa Marketplace',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/secret_stash.png',
      id: 'secret-stash.io',
      url: 'https://secret-stash.io',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Cosmize Experience',
      icon: 'https://app.cosmize.io/TemplateData/img/favicon.ico',
      id: 'app.cosmize.io',
      url: 'https://app.cosmize.io',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'ArtZero.io - NFT Marketplace for Aleph Zero Blockchain',
      icon: 'https://alephzero.artzero.io/assets/favicon/apple-touch-icon.png',
      id: 'alephzero.artzero.io',
      url: 'https://alephzero.artzero.io',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'InkWhale.net - Staking and Yield Farming Platform on Aleph Zero',
      icon: 'https://inkwhale.net/apple-touch-icon.png',
      id: 'inkwhale.net',
      url: 'https://inkwhale.net',
      categories: ['defi'],
    },
    {
      name: 'AzeroPunks',
      icon: 'https://mint.azeropunks.com/favicon.ico',
      id: 'mint.azeropunks.com/#/welcome',
      url: 'https://mint.azeropunks.com/#/welcome',
      categories: ['defi'],
    },
    {
      name: 'Polkasafe',
      icon: 'https://app.polkasafe.xyz/logo192.png',
      id: 'app.polkasafe.xyz',
      url: 'https://app.polkasafe.xyz/',
      categories: ['defi'],
    },
    {
      name: 'Bananaswap',
      icon: 'https://www.bananaswap.app/favicon.png',
      id: 'www.bananaswap.app/#/swap',
      url: 'https://www.bananaswap.app/#/swap',
      categories: ['defi'],
    },
    {
      name: 'Bounce',
      icon: 'https://app.bounce.finance/favicon.svg',
      id: 'app.bounce.finance/market',
      url: 'https://app.bounce.finance/market',
      categories: ['defi'],
    },
    {
      name: 'HashKey DID',
      icon: 'https://www.hashkey.id/favicon.ico',
      id: 'www.hashkey.id/home',
      url: 'https://www.hashkey.id/home',
      categories: ['defi'],
    },
    {
      name: 'Bluez',
      icon: 'https://bluez.app/favicon-96x96.png',
      id: 'bluez.app',
      url: 'https://bluez.app/',
      categories: ['defi'],
    },
    {
      name: 'Mandala',
      icon: 'https://enterthemandala.app/SriChakraRainbow.png',
      id: 'enterthemandala.app/HomePage',
      url: 'https://enterthemandala.app/HomePage',
      categories: ['defi'],
    },
    {
      name: 'Mangata - The DEX of the future',
      icon: 'https://uploads-ssl.webflow.com/63e60f4a25768f19afed1e9a/63e634365f7ee2ca7ca65ee6_mga-website-favicon.png',
      id: 'www.mangata.finance',
      url: 'https://www.mangata.finance/',
      categories: ['defi'],
    },
    {
      name: 'DAM',
      icon: 'https://app.dam.finance/favicon.ico',
      id: 'app.dam.finance',
      url: 'https://app.dam.finance/',
      categories: ['defi'],
    },
    {
      name: 'Acala Platform',
      icon: 'https://apps.acala.network/favicon.ico',
      id: 'apps.acala.network',
      url: 'https://apps.acala.network/',
      categories: ['defi'],
    },
    {
      name: 'Equilibrium',
      icon: '',
      id: 'app.equilibrium.io',
      url: 'https://app.equilibrium.io/',
      categories: ['defi'],
    },
    {
      name: 'Gear Technologies | Crypto. Smarter.',
      icon: 'https://www.gear-tech.io/favicon.ico',
      id: 'www.gear-tech.io',
      url: 'https://www.gear-tech.io/',
      categories: ['defi'],
    },
    {
      name: 'Karura Platform',
      icon: 'https://apps.karura.network/apple-touch-icon.png',
      id: 'apps.karura.network',
      url: 'https://apps.karura.network/',
      categories: ['defi'],
    },
    {
      name: 'MoonFit - Web3 & NFT Lifestyle App',
      icon: 'https://app.moonfit.xyz/logo-32x32.ico',
      id: 'app.moonfit.xyz/nft-sale',
      url: 'https://app.moonfit.xyz/nft-sale',
      categories: ['defi'],
    },
    {
      name: 'Sirius Finance',
      icon: 'https://app.sirius.finance/apple-touch-icon.png',
      id: 'app.sirius.finance/#/swap',
      url: 'https://app.sirius.finance/#/swap',
      categories: ['defi'],
    },
    {
      name: 'Sub ID: Substrate Addresses, Balances, Crowdloans and NFTs',
      icon: '',
      id: 'sub.id',
      url: 'https://sub.id/',
      categories: ['defi'],
    },
    {
      name: "PolkaVerse – Polkadot's Premier Social Network",
      icon: '',
      id: 'polkaverse.com',
      url: 'https://polkaverse.com/',
      categories: ['defi'],
    },
    {
      name: 'Swap - Polkaswap',
      icon: 'https://polkaswap.io/favicon.ico',
      id: 'polkaswap.io',
      url: 'https://polkaswap.io/',
      categories: ['defi'],
    },
    {
      name: 'PrivaDEX',
      icon: 'https://app.privadex.xyz/privadex_favicon.png',
      id: 'app.privadex.xyz',
      url: 'https://app.privadex.xyz/',
      categories: ['defi'],
    },
    {
      name: 'Notifi',
      icon: 'https://notifi.network/favicon.svg',
      id: 'notifi.network/dashboard',
      url: 'https://notifi.network/dashboard',
      categories: ['defi'],
    },
    {
      name: 'Kanaria Skybreach',
      icon: 'https://skybreach.app/icons/favicon.ico',
      id: 'skybreach.app',
      url: 'https://skybreach.app/',
      categories: ['defi'],
    },
    {
      name: 'Spacers NFT Pods Sale',
      icon: 'https://pods.spacers.app/favicon.png',
      id: 'pods.spacers.app',
      url: 'https://pods.spacers.app/',
      categories: ['defi'],
    },
    {
      name: 'YieldBay',
      icon: 'https://list.yieldbay.io/favicon/favicon.ico',
      id: 'list.yieldbay.io',
      url: 'https://list.yieldbay.io/',
      categories: ['defi'],
    },
    {
      name: 'FiDi',
      icon: 'https://app.fidi.tech/assets/favicon.ico',
      id: 'app.fidi.tech',
      url: 'https://app.fidi.tech/',
      categories: ['defi'],
    },
    {
      name: 'Braindex | Smart Dex Aggregator',
      icon: '',
      id: 'www.braindex.io/swap',
      url: 'https://www.braindex.io/swap',
      categories: ['defi'],
    },
    {
      name: 'Uniswap Interface',
      icon: 'https://app.uniswap.org/favicon.png',
      id: 'app.uniswap.org',
      url: 'https://app.uniswap.org/',
      categories: ['defi'],
    },
    {
      name: 'Swap - Curve',
      icon: 'https://curve.fi/apple-touch-icon.png',
      id: 'curve.fi',
      url: 'https://curve.fi/',
      categories: ['defi'],
    },
    {
      name: 'Aave - Open Source Liquidity Protocol',
      icon: 'https://app.aave.com/favicon.ico',
      id: 'app.aave.com',
      url: 'https://app.aave.com/',
      categories: ['defi'],
    },
    {
      name: 'Liquid Staking for Digital Tokens',
      icon: 'https://lido.fi/static/images/favicon/apple-touch-icon.png',
      id: 'lido.fi/#networks',
      url: 'https://lido.fi/#networks',
      categories: ['defi'],
    },
    {
      name: 'Blur: NFT Marketplace for Pro Traders',
      icon: 'https://blur.io/favicons/180.png',
      id: 'blur.io',
      url: 'https://blur.io/',
      categories: ['defi'],
    },
    {
      name: '1inch - DeFi / DEX aggregator on Ethereum, Binance Smart Chain, Optimism, Polygon, Arbitrum',
      icon: 'https://app.1inch.io/assets/favicon/apple-touch-icon.png',
      id: 'app.1inch.io',
      url: 'https://app.1inch.io/',
      categories: ['defi'],
    },
    {
      name: 'Chainlist',
      icon: 'https://chainlist.org/favicon.ico',
      id: 'chainlist.org',
      url: 'https://chainlist.org/',
      categories: ['defi'],
    },
    {
      name: 'Multichain',
      icon: 'https://app.multichain.org/favicon.ico',
      id: 'app.multichain.org/#/router',
      url: 'https://app.multichain.org/#/router',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Portal Token Bridge',
      icon: 'https://www.portalbridge.com/favicon.ico',
      id: 'www.portalbridge.com',
      url: 'https://www.portalbridge.com/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
    {
      name: 'Verse DEX | Bitcoin.com’s official decentralized exchange',
      icon: 'https://verse.bitcoin.com/images/favicon.png',
      id: 'verse.bitcoin.com/#',
      url: 'https://verse.bitcoin.com/#/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
    },
  ],
};
