import { MissionInfo } from 'types/missionPool';

export const missionPoolsBackupData: MissionInfo[] = [
  {
    id: 21,
    name: "Win $2000 USDT Prize Pool with Creditcoin's Real-World EVM Gamified Testnet campaign",
    status: 'live',
    ordinal: 81,
    description:
      "The moment you’ve been waiting for! It’s time to showcase your Testnet credentials for a chance to win from the bonus $2,000 USDT prize pool!\n\nSimply grab Testnet tokens from the Discord Testnet Faucet and start exploring the protocol's and Testnet's main features. Validators and nominators should complete on-chain tasks with your Substrate wallet, while developers can start executing smart contracts using their submitted EVM wallet. Tasks include:\n\n- Using the faucets on Discord to receive Testnet tokens.\n- Completing a range of on-chain activities (e.g. validating, staking, transferring, etc.)\n- Executing smart contracts (developers)\n\nAs you dive deeper into Testnet, write a post or thread on X about Creditcoin with the required tags: $CTC #RWA #Layer1\n\nThen earn bonus points by referring your friends to maximize your chances of winning from the $2k USDT prize pool.\n\nParticipate and win by completing the quest now!",
    start_time: '2024-04-01T12:00:00.000Z',
    end_time: '2024-06-01T04:00:00.000Z',
    url: 'https://bit.ly/ctc_questn',
    twitter_url: 'https://twitter.com/Creditcoin',
    reward: '50 USDT each',
    total_winner: '40',
    total_supply: null,
    tags: ['lucky_draw'],
    campaign_url: 'https://creditcoin.org/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/creditcoin_448a940bb0.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Creditcoin_Quest_N_campaign_328d460006.png',
    chains: ['creditcoinTest', 'creditcoinTestEvm'],
  },
  {
    id: 23,
    name: 'Split the pool of 1.1M $PINK with Moonwell is PINK campaign',
    status: 'live',
    ordinal: 82,
    description:
      "Moonwell is PINK!\n\nSupply $25 worth of xcDOT liquidity\nSupply $25 worth of GLMR liquidity\nStake $25 worth of WELL liquidity\nVote on a governance proposal\nLike & retweet the campaign announcement\n\nComplete all tasks to win an equal share of Moonwell's PINK token allocation.",
    start_time: '2024-04-06T04:00:00.000Z',
    end_time: '2024-05-07T04:00:00.000Z',
    url: 'https://bit.ly/pink_well_galxe',
    twitter_url: 'https://twitter.com/MoonwellDeFi',
    reward: '1.1M $PINK',
    total_winner: 'N/A',
    total_supply: null,
    tags: ['fcfs'],
    campaign_url: 'https://moonwell.fi/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/moonwell_728c173d60.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Moonwell_is_PINK_Galxe_campaign_98368861cd.png',
    chains: ['moonbeam'],
  },
  {
    id: 25,
    name: 'Win $500 in DOT with The Unique Network NFT contest',
    status: 'live',
    ordinal: 83,
    description:
      'Celebrating Polkadot at the Indianapolis 500! \n\nTo celebrate and show the support for Conor Daly at the Indianapolis 500, Unique Network is hosting an NFT competition to get fans involved in the excitement!\n\nJoin us for a chance to be one of the 25 lucky participants to win $500 in DOT! 🏆\n\nEnter the competition here 👇\nhttps://zealy.io/cw/unique\n\nWeek 1’s Tasks:\n- Share your Polkadot wallet address\n- Mint NFTs\n- Share them on Twitter!\n\nCompetition Details:\n- Runs from April 16 - May 3, 2024\n- Different tasks each week\n- Be in the chance to win $500 in DOT\n- Show your support for Conor, as he races with the Polkadot community behind him!',
    start_time: '2024-04-15T17:00:00.000Z',
    end_time: '2024-05-15T16:59:00.000Z',
    url: 'https://zealy.io/cw/unique/questboard',
    twitter_url: 'https://twitter.com/Unique_NFTchain',
    reward: '$500 in DOT',
    total_winner: '25',
    total_supply: null,
    tags: ['lucky_draw'],
    campaign_url: 'https://unqnft.io/market',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/unique_network_b207ab1ac7.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Unique_NFT_contest_9436e9de22.jpg',
    chains: ['unique_network'],
  },
  {
    id: 26,
    name: "Join Tanssi's Let's Forkin' Dance incentivized testnet campaign to share the pool of 4M tokens",
    status: 'live',
    ordinal: 84,
    description:
      "Let's Forkin' Dance Is Here!\n\n'Let's Forkin' Dance' - Tanssi's incentivized testnet campaign is a mix of on-chain and off-chain quests designed for the Tanssi community. Whether you're a developer, a casual user, or a key network supporter, there's something for you.\n\n1% of the Tanssi Network is reserved for this campaign - which is the first campaign ever hosted by the Tanssi Foundation. 40% of the incentives pool, which amounts to 4M tokens, will be allocated to the Tanssians track with only the top 4000 participants receiving it. Stay tuned that more is coming up!\n\nThe campaign launches on April 30, 2024. To stay ahead, set an alert or join the Tanssi communities, ensuring you're one of the first to access the LFD campaign portal.\n\nLFD plays a critical role in the upcoming launch of the Tanssi Network. Engaged participants not only earn incentives but also get to significantly contribute to the network's live environment.",
    start_time: '2024-04-29T17:00:00.000Z',
    end_time: null,
    url: 'https://lfd.tanssi.network/',
    twitter_url: 'https://twitter.com/TanssiNetwork',
    reward: '4M Tanssi tokens',
    total_winner: '4000',
    total_supply: null,
    tags: ['points'],
    campaign_url: 'https://www.tanssi.network/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/tanssi_2e13dc9c66.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Tanssi_Network_Let_s_Forkin_Dance_ebcf7a8a63.jpg',
    chains: ['dancebox'],
  },
  {
    id: 20,
    name: '250K $STELLA + 1.19M $PINK rewards + exclusive OG NFTs with stDOT Boost Campaign',
    status: 'archived',
    ordinal: 85,
    description:
      'A dedicated campaign to spearhead growth for one of the leading DOT LSDs on Polkadot: stDOT!\n\nHere’s what you can earn;\n💰 STELLA & PINK Airdrop\n✅ stDOT Staking Rewards (18.4%)\n👨‍🌾 stDOT Farm Rewards\n🌟 Exclusive OG NFT\n\nAre you ready? 🚀',
    start_time: '2024-03-27T16:00:00.000Z',
    end_time: '2024-04-27T00:00:00.000Z',
    url: 'https://bit.ly/stdot_stellaswap',
    twitter_url: 'https://twitter.com/StellaSwap',
    reward: '250K $STELLA & 1.19M $PINK',
    total_winner: 'N/A',
    total_supply: null,
    tags: ['fcfs', 'points'],
    campaign_url: 'https://stellaswap.com/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/stellaswap_5112d4145b.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/st_DOT_BOOST_campaign_09a8bcbce9.png',
    chains: ['moonbeam', 'polkadot'],
  },
  {
    id: 22,
    name: "Win a share of 10,000 USD prize pool with with Avail's debut campaign on Galxe",
    status: 'archived',
    ordinal: 85,
    description:
      "Accelerate the Unification of Web3 with Avail's Debut Campaign!\n\nHurry and participate in Avail's debut quest to claim your point reward.\n\nBy participating, you’ll have the chance to be one of the few lucky winners to share a grand prize pool of $10,000 via raffle!\n\nStay connected with the updates, and unlock special bonus points with different tasks to increase your chances.\n\nStart your Avail quest journey now.",
    start_time: '2024-03-31T18:30:00.000Z',
    end_time: '2024-04-14T18:30:00.000Z',
    url: 'https://bit.ly/avail_galxe',
    twitter_url: 'https://twitter.com/AvailProject',
    reward: '10,000 USD',
    total_winner: 'N/A',
    total_supply: null,
    tags: ['lucky_draw'],
    campaign_url: 'https://www.availproject.org/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/avail_16bb040742.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Avail_Galxe_campaign_ca74389678.jpg',
    chains: ['goldberg_testnet'],
  },
  {
    id: 24,
    name: 'Join Airlyft is $PINK campaign to share a 430,000 $PINK prize pool',
    status: 'archived',
    ordinal: 86,
    description:
      "Get ready for an out-of-this-world opportunity to win big in the $PINK campaign. In this collaboration between Moonbeam and Airlyft, we're launching a massive $PINK token pool that could shower you with up to 500,000 $PINK tokens!\n\nTo increase your chances of winning, you'll need to perform on-chain transactions every single day. Consistency is key to unlocking the ultimate $PINK treasure trove. Mark your calendars and get ready for a daily ritual of transactions that will make your odds of winning soar higher! 🌌\n\nRewards\n1. 10 winners with the best Meme on Twitter will be eligible for a 70,000 $PINK pool\n2. 200 winners from random raffle will be eligible for a 430,000 $PINK pool\n\nDon't miss this stellar opportunity to join the $PINK token craze 🎀. The countdown has begun. Strap in, crypto explorers, and let the $PINK Token commence! 🚀",
    start_time: '2024-04-05T12:30:00.000Z',
    end_time: '2024-04-18T12:30:00.000Z',
    url: 'https://bit.ly/pink_airlyft',
    twitter_url: 'https://twitter.com/airlyftone',
    reward: '430,000 $PINK',
    total_winner: '200',
    total_supply: null,
    tags: ['lucky_draw'],
    campaign_url: 'https://airlyft.one/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/airlyft_f23e57e74e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Airlyft_is_PINK_campaign_8ca0addbbd.png',
    chains: ['moonbeam'],
  },
  {
    id: 19,
    name: 'Share 2500 $ASTR prize pool + FREE NFT with Airlyft Campaign: zkEVM by Astar ',
    status: 'archived',
    ordinal: 89,
    description:
      "Astar's zkEVM mainnet is LIVE!  Be among the first to explore.\n\nLevel up your Web3 game with Airlyft's zkEVM event!  Complete the challenges and score awesome prizes:\n- Every winner gets a limited-edition Astar NFT\n- 50 lucky explorers will share a 2500 $ASTR prize pool!\n\nThink you've got what it takes to build the future of Web3?  Prove it, and the rewards are yours!",
    start_time: '2024-03-11T04:30:00.000Z',
    end_time: '2024-04-11T04:30:00.000Z',
    url: 'https://bit.ly/zkevmastar_airlyft',
    twitter_url: 'https://twitter.com/AstarNetwork',
    reward: '50 $ASTR and Astar NFT',
    total_winner: '50',
    total_supply: '2500 $ASTR',
    tags: ['lucky_draw'],
    campaign_url: 'https://astar.network/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/astar_zkevm_e3c6c227da.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Airlyft_zk_EVM_by_Astar_c1b35d5416.png',
    chains: ['astarZkEvm'],
  },
  {
    id: 13,
    name: 'vDOT is DED',
    status: 'archived',
    ordinal: 90,
    description:
      'Mint vDOT to show how DED it is!\nThe more vDOT the more DED for the incoming airdrop.\n\nSnapshot to be executed soon...',
    start_time: '2024-02-27T09:00:00.000Z',
    end_time: '2024-03-10T12:00:00.000Z',
    url: 'https://bit.ly/vdotisded',
    twitter_url: null,
    reward: '10 BNC',
    total_winner: '100',
    total_supply: '1,000 BNC',
    tags: ['lucky_draw'],
    campaign_url: 'https://bifrost.app/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/vdotisded_e4faf83730.webp',
    chains: ['bifrost_dot'],
  },
  {
    id: 15,
    name: 'Galxe Campaign: $10,000 USDT + AiPixel Land Reward to 10,000 Participants',
    status: 'archived',
    ordinal: 91,
    description:
      '👀 What’s in it for you?🎁\n\n- 1 Million NUUM Treasury: 1 Million NUUM Treasury: I’ll distribute rewards from our massive treasury to brilliant minds that help me to shape the future. Ask your first question wisely… 😘\n- Land for 10,000 participants: Secure your digital territory as one of the first 10,000 campaigners. 🏞️\n$10,000 USDT Giveaway: 20 lucky participants will win a share of this bounty! 💰\n- Join our quest to shape this universe 🌐. Your ideas can earn you land, NUUM, and USDT!',
    start_time: '2024-02-22T23:00:00.000Z',
    end_time: '2024-03-07T23:00:00.000Z',
    url: 'https://galxe.com/bitcountry/campaign/GCym8t4A89',
    twitter_url: null,
    reward: '500 USDT',
    total_winner: '200',
    total_supply: '10,000 USDT',
    tags: ['lucky_draw', 'points'],
    campaign_url: 'https://mnet.io/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bit_country_continuum_5f92dd7fcc.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/mnet_campaign_d269d1136a.png',
    chains: ['continuum_network'],
  },
  {
    id: 16,
    name: 'Zealy Campaign: $10,000 USDT + AiPixel Land Reward to 10,000 Participants',
    status: 'archived',
    ordinal: 92,
    description:
      '👀 What’s in it for you?🎁\n\n- 1 Million NUUM Treasury: 1 Million NUUM Treasury: I’ll distribute rewards from our massive treasury to brilliant minds that help me to shape the future. Ask your first question wisely… 😘\n- Land for 10,000 participants: Secure your digital territory as one of the first 10,000 campaigners. 🏞️\n$10,000 USDT Giveaway: 20 lucky participants will win a share of this bounty! 💰\n- Join our quest to shape this universe 🌐. Your ideas can earn you land, NUUM, and USDT!',
    start_time: '2024-02-22T23:00:00.000Z',
    end_time: '2024-03-07T23:00:00.000Z',
    url: 'https://bit.ly/mnetaipixel',
    twitter_url: null,
    reward: '500 USDT',
    total_winner: '200',
    total_supply: '10,000 USDT',
    tags: ['lucky_draw', 'points'],
    campaign_url: 'https://mnet.io/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bit_country_continuum_5f92dd7fcc.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/mnet_zealy_campaign_1e2101ab35.jpeg',
    chains: ['continuum_network'],
  },
  {
    id: 3,
    name: 'Omni LS - Moonbeam campaign',
    status: 'archived',
    ordinal: 93,
    description:
      'The Moonbeam x Omni LS dApp Campaign is the first in a series of events that will also involve Polkadot ecosystem Wallets, as well as Polkadot itself.',
    start_time: '2023-10-13T11:00:00.000Z',
    end_time: '2023-11-22T00:00:00.000Z',
    url: 'https://airlyft.one/bifrost-finance/omni-ls-moonbeam',
    twitter_url: 'https://twitter.com/BifrostFinance',
    reward: '1 LS_MOONBEAM',
    total_winner: 'N/A',
    total_supply: '80,000,000 BNC',
    tags: ['fcfs'],
    campaign_url: 'https://airlyft.one/bifrost-finance/omni-ls-moonbeam',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/bifrost_moonbeam_a82f6c23ef.webp',
    chains: ['bifrost_dot', 'moonbeam'],
  },
  {
    id: 6,
    name: 'Road To The Unlock!',
    status: 'archived',
    ordinal: 94,
    description:
      'By following the whole campaign and testing the new Omni LS & partners dapps, you will be able to collect several NFTs along the road. By collecting all NFTs you will be eligible for the final NFT and a 20,000 $BNC tokens airdrop to share!',
    start_time: '2023-10-11T11:00:00.000Z',
    end_time: '2023-10-24T11:00:00.000Z',
    url: 'https://airlyft.one/bifrost-finance/road-to-the-unlock',
    twitter_url: 'https://twitter.com/BifrostFinance',
    reward: '5 XP & 13 Fuel',
    total_winner: 'N/A',
    total_supply: '80,000,000 BNC',
    tags: ['points'],
    campaign_url: 'https://airlyft.one/bifrost-finance/road-to-the-unlock',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/bifrost_moonbeam_a82f6c23ef.webp',
    chains: ['bifrost_dot'],
  },
  {
    id: 8,
    name: 'Stake DOT Earn Many',
    status: 'archived',
    ordinal: 95,
    description:
      'From Oct 24 to Nov 07, take part in the most comprehensive staking campaign ever in the Polkadot ecosystem with Polkadot nomination pools, Acala, Bifrost, and Parallel liquid staking, and Interlay and Moonwell lending is happening at SubWallet Web Dashboard!\n\nUsers who have staked and earned a DOT Power Staker NFT are eligible to participate in this Airlyft campaign and share a reward pool of $1,000.\n\nNote: 100 winners are selected based on a combination of points, content quality, and social media engagement. Each winner will receive 10 USDT on Polkadot Asset Hub.\n\nAdditional information: Users who stake with Acala, Bifrost, and Parallel from Oct 24 to Nov 07 have the chance to share exclusive reward pools, including 80K ACA, 5K BNC, and 1M PARA. More details are available in SubWallet Earning FAQs.',
    start_time: '2023-10-24T12:00:00.000Z',
    end_time: '2023-11-08T00:00:00.000Z',
    url: 'https://airlyft.one/subwallet/stake-dot-earn-many-by-subwallet',
    twitter_url: 'https://twitter.com/subwalletapp',
    reward: '1,000 USDT',
    total_winner: '100',
    total_supply: 'N/A',
    tags: ['manual_selection'],
    campaign_url: 'https://web.subwallet.app/home/earning/overview',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/wallet_connect_9ed43a1b95.png',
    backdrop_image: 'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/image_2_2e3a8054b5.png',
    chains: ['polkadot', 'bifrost_dot', 'acala', 'parallel', 'interlay', 'moonbeam'],
  },
  {
    id: 7,
    name: 'Zeitgeist x CoinDesk Indices',
    status: 'archived',
    ordinal: 96,
    description:
      'Zeitgeist is partnering with CoinDesk Indices to create a unique trading experience to give traders an edge in the broader market. By participating in Zeitgeist prediction markets surrounding specific CoinDesk Indices, traders are able to capitalize on their crypto knowledge, while other users can view the prediction market data and gain an informational edge on the direction of crypto prices in general!',
    start_time: '2023-10-04T14:30:00.000Z',
    end_time: '2023-11-01T04:00:00.000Z',
    url: 'https://airlyft.one/zeitgeist/coindesk-index',
    twitter_url: 'https://twitter.com/ZeitgeistPM',
    reward: '50 ZTG',
    total_winner: '888',
    total_supply: '100,054,784 ZTG',
    tags: ['manual_selection'],
    campaign_url: 'https://airlyft.one/zeitgeist/coindesk-index',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/zeitgeist_a72652f11c.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/zeitgeist_6ca1f96bd6.webp',
    chains: ['zeitgeist'],
  },
  {
    id: 5,
    name: 'Polkadot Unlock Harvest',
    status: 'archived',
    ordinal: 97,
    description:
      'The goal of the event is to pave the road for the DOT unlock event on October 24th. Introducing users to the dApp and familiarizing you with its mechanics and the assets within, you will be allowed to take advantage of the benefits of Bifrost Liquid Staking. The Moonbeam x Omni LS dApp Campaign is the first in a series of events that will also involve Polkadot ecosystem Wallets, as well as Polkadot itself.',
    start_time: '2023-10-24T11:00:00.000Z',
    end_time: '2023-11-22T12:00:00.000Z',
    url: 'https://airlyft.one/bifrost-finance/polkadot-unlock-harvest',
    twitter_url: 'https://twitter.com/BifrostFinance',
    reward: '1 LS_POLKADOT',
    total_winner: 'N/A',
    total_supply: '80,000,000 BNC',
    tags: ['fcfs'],
    campaign_url: 'https://airlyft.one/bifrost-finance/polkadot-unlock-harvest',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/bifrost_moonbeam_a82f6c23ef.webp',
    chains: ['bifrost_dot'],
  },
  {
    id: 4,
    name: 'Omni LS - Ecosystem Wallets campaign',
    status: 'archived',
    ordinal: 98,
    description:
      'One of three events leading up to the Unlock of +100 Million $DOT from the first parachain crowdloans, on Polkadot.',
    start_time: '2023-10-19T11:00:00.000Z',
    end_time: '2023-11-22T12:00:00.000Z',
    url: 'https://airlyft.one/bifrost-finance/omni-ls-polkadot-wallets',
    twitter_url: 'https://twitter.com/BifrostFinance',
    reward: '1 LS_WALLETS',
    total_winner: 'N/A',
    total_supply: '80,000,000 BNC',
    tags: ['fcfs'],
    campaign_url: 'https://airlyft.one/bifrost-finance/omni-ls-polkadot-wallets',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/bifrost_moonbeam_a82f6c23ef.webp',
    chains: ['bifrost_dot'],
  },
  {
    id: 10,
    name: '$DED is LIVE',
    status: 'archived',
    ordinal: 99,
    description:
      'Hop in to explore DOT Is $DED Zealy community, and pledge yourself to $DED!\n\nOver 4000 DOT in rewards across 3 stages!\n\nPhase $DED is LIVE - Reward Pool: 1.400 DOT\n\n📅 Duration: 02/12 - 02/26 (3pm CET)\n',
    start_time: '2024-02-11T17:00:00.000Z',
    end_time: '2024-02-26T14:00:00.000Z',
    url: 'https://bit.ly/zealyded',
    twitter_url: 'https://twitter.com/dotisded',
    reward: '1,400 DOT',
    total_winner: null,
    total_supply: null,
    tags: ['points'],
    campaign_url: 'https://www.dotisded.io/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/ded_277c75073c.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/GGJJW_63_Ws_AER_Hdh_fef9a37345.jpeg',
    chains: ['polkadot'],
  },
  {
    id: 11,
    name: 'PLOT the vDOT with Zeitgeist',
    status: 'archived',
    ordinal: 99,
    description: 'Mint vDOT and predict Markets on Zeitgeist !\n20 random winners will share 500 $BNC and 2000 $ZTG.',
    start_time: '2024-01-31T17:00:00.000Z',
    end_time: '2024-03-01T11:00:00.000Z',
    url: 'https://bit.ly/airlyft_bifrost_zei',
    twitter_url: 'https://twitter.com/BifrostFinance',
    reward: '500 $BNC and 2000 $ZTG',
    total_winner: '20',
    total_supply: null,
    tags: ['lucky_draw'],
    campaign_url: 'https://bifrost.app/',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/bifrost_polkadot_b85046fb9e.png',
    backdrop_image:
      'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/GFL_7p1d_WUA_Eschq_f6004397f2.jpeg',
    chains: ['bifrost_dot', 'zeitgeist'],
  },
  {
    id: 18,
    name: '80,000 SUB up for grabs: Join Grill x SubWallet content contest now!',
    status: 'archived',
    ordinal: 100,
    description:
      'Hey fam!\n\nParticipate in Grill’s Grand Content Contest in collaboration with SubWallet and share a 80,000 SUB tokens prize pool!\n\nDuration: March 11-17\n\n',
    start_time: '2024-03-11T16:45:00.000Z',
    end_time: '2024-03-17T16:45:00.000Z',
    url: 'https://grillapp.net/6479/80-000-sub-up-for-grabs-join-grill-x-sub-wallet-content-91982?ref=6479',
    twitter_url: 'https://twitter.com/subwalletapp',
    reward: '80,000 SUB',
    total_winner: '35',
    total_supply: null,
    tags: ['manual_selection', 'lucky_draw'],
    campaign_url: 'https://grillapp.net/6479?ref=6479',
    logo: 'https://static-data.subwallet.app/airdrop-campaigns/images/logo/Logo_Gradient_Background_Black_cbf44085a7.png',
    backdrop_image: 'https://static-data.subwallet.app/airdrop-campaigns/images/backdrop_image/Revised_641a84b12b.png',
    chains: ['subsocial_x'],
  },
];
