import { SIGN_MODE } from 'types/signer';

export const MODE_CAN_SIGN: SIGN_MODE[] = [SIGN_MODE.PASSWORD, SIGN_MODE.QR];

export const MANUAL_CANCEL_EXTERNAL_REQUEST = 'MANUAL_CANCEL_EXTERNAL_REQUEST';
