export const CHAIN_TYPE_MAP = {
  relay: [
    'polkadot',
    'kusama',
    'aleph',
    'alephTest',
    'westend',
    'polkadex',
    'polkadexTest',
    'ternoa',
    'ternoa',
    'ternoa_alphanet',
  ],
  para: [
    'moonbeam',
    'moonbase',
    'moonriver',
    'turing',
    'turingStaging',
    'bifrost',
    'bifrost_testnet',
    'calamari',
    'calamari_test',
  ],
  astar: ['astar', 'shiden', 'shibuya'],
  amplitude: ['amplitude', 'amplitude_test', 'kilt', 'kilt_peregrine'],
};
