import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { KeypairType } from '@polkadot/util-crypto/types';
import { TransferNftParams } from 'stores/types';

export type RootStackParamList = {
  LockScreen: undefined;
  LoadingScreen: undefined;
  Home: undefined;
  CreateAccount: { keyTypes: KeypairType };
  QrScanner: undefined;
  AccountsScreen: undefined;
  EditAccount: { address: string; name: string };
  RemoveAccount: { address: string };
  RestoreJson: undefined;
  ExportPrivateKey: { address: string };
  Settings: undefined;
  NetworkSelect: undefined;
  ImportSecretPhrase: { keyTypes: KeypairType };
  ImportPrivateKey: undefined;
  NetworksSetting: undefined;
  SendFund: { selectedAccount: string; selectedNetworkKey: string; selectedToken: string };
  Languages: undefined;
  Security: undefined;
  PinCode: { screen: 'NewPinCode' | 'ChangePinCode' | 'TurnoffPinCode' };
  ExportJson: undefined;
  BrowserSearch: undefined;
  BrowserTab: { url: string; name: string };
  ConfirmationPopup: undefined;
  FavouritesGroupDetail: undefined;
  HistoryGroupDetail: undefined;
  DAppAccess: undefined;
  DAppAccessDetail: { origin: string; accountAuthType: string };
  WebViewDebugger: undefined;
  ImportEvmNft: undefined;
  SendNft: TransferNftParams;
};

export type NavigationProps = NativeStackScreenProps<RootStackParamList>;
export type RootNavigationProps = NavigationProps['navigation'];
export type RootRouteProps = NavigationProps['route'];
export type CreateAccountProps = NativeStackScreenProps<RootStackParamList, 'CreateAccount'>;
export type ImportSecretPhraseProps = NativeStackScreenProps<RootStackParamList, 'ImportSecretPhrase'>;
export type PinCodeProps = NativeStackScreenProps<RootStackParamList, 'PinCode'>;
export type SendFundProps = NativeStackScreenProps<RootStackParamList, 'SendFund'>;
export type EditAccountProps = NativeStackScreenProps<RootStackParamList, 'EditAccount'>;
export type ExportPrivateKeyProps = NativeStackScreenProps<RootStackParamList, 'ExportPrivateKey'>;
export type RemoveAccountProps = NativeStackScreenProps<RootStackParamList, 'RemoveAccount'>;
export type SendNftProps = NativeStackScreenProps<RootStackParamList, 'SendNft'>;
export type DAppAccessDetailProps = NativeStackScreenProps<RootStackParamList, 'DAppAccessDetail'>;
export type BrowserTabProps = NativeStackScreenProps<RootStackParamList, 'BrowserTab'>;
