// Note: All keys must be lowercase

import React from 'react';

const EnglishLogo = React.lazy(() => import('./languages/english.svg'));
const VietnameseLogo = React.lazy(() => import('./languages/vietnamese.svg'));
const ChineseLogo = React.lazy(() => import('./languages/chinese.svg'));
const FranchiseLogo = React.lazy(() => import('./languages/franchise.svg'));
const JapaneseLogo = React.lazy(() => import('./languages/japan.svg'));
const RussianLogo = React.lazy(() => import('./languages/russia.svg'));
const XLogo = React.lazy(() => import('./x-logo.svg'));
const RestartLogo = React.lazy(() => import('./restart-logo.svg'));

export const ImageLogosMap = {
  parity: require('./207.vault.png'),
  keystone: require('./202.keystone.png'),
  subwallet: require('./00.subwallet.png'),
  __qr_code__: require('./203.__qr_code__.png'),
  transak: require('./buy/transak.png'),
  moonpay: require('./buy/moonpay.png'),
  onramper: require('./buy/onramper.png'),
  banxa: require('./buy/banxa.png'),
  coinbase: require('./buy/coinbase.png'),
  meld: require('./buy/meld.png'),
  default: require('./default.png'),
  stellaswap: require('./stellaswap.png'),
  chain_flip_mainnet: require('./chainflip-mainnet.png'),
  chain_flip_testnet: require('./chainflip-mainnet.png'),
  hydradx_mainnet: require('./hydradx_main.png'),
  hydradx_testnet: require('./hydradx_main.png'),
  simple_swap: require('./simple-swap.png'),
  currency_brl: require('./CurrencyBRL.png'),
  currency_cny: require('./CurrencyCNY.png'),
  currency_hkd: require('./CurrencyHKD.png'),
  currency_vnd: require('./CurrencyVND.png'),
  polkadot_assethub: require('./polkadot-asset-hub.png'),
  kusama_assethub: require('./kusama-asset-hub.png'),
  rococo_assethub: require('./uniswap.png'),
  uniswap: require('./rococo-asset-hub.png'),
  ordinal_rune: require('./ordinal_rune.png'),
  kyber: require('./kyber.png'),
  'subnet-0': require('./bittensor/subnet-0.png'),
  'subnet-1': require('./bittensor/subnet-1.png'),
  'subnet-2': require('./bittensor/subnet-2.png'),
  'subnet-3': require('./bittensor/subnet-3.png'),
  'subnet-4': require('./bittensor/subnet-4.png'),
  'subnet-5': require('./bittensor/subnet-5.png'),
  'subnet-6': require('./bittensor/subnet-6.png'),
  'subnet-7': require('./bittensor/subnet-7.png'),
  'subnet-8': require('./bittensor/subnet-8.png'),
  'subnet-9': require('./bittensor/subnet-9.png'),
  'subnet-10': require('./bittensor/subnet-10.png'),
  'subnet-11': require('./bittensor/subnet-11.png'),
  'subnet-12': require('./bittensor/subnet-12.png'),
  'subnet-13': require('./bittensor/subnet-13.png'),
  'subnet-14': require('./bittensor/subnet-14.png'),
  'subnet-15': require('./bittensor/subnet-15.png'),
  'subnet-16': require('./bittensor/subnet-16.png'),
  'subnet-17': require('./bittensor/subnet-17.png'),
  'subnet-18': require('./bittensor/subnet-18.png'),
  'subnet-19': require('./bittensor/subnet-19.png'),
  'subnet-20': require('./bittensor/subnet-20.png'),
  'subnet-21': require('./bittensor/subnet-21.png'),
  'subnet-22': require('./bittensor/subnet-22.png'),
  'subnet-23': require('./bittensor/subnet-23.png'),
  'subnet-24': require('./bittensor/subnet-24.png'),
  'subnet-25': require('./bittensor/subnet-25.png'),
  'subnet-26': require('./bittensor/subnet-26.png'),
  'subnet-27': require('./bittensor/subnet-27.png'),
  'subnet-28': require('./bittensor/subnet-28.png'),
  'subnet-29': require('./bittensor/subnet-29.png'),
  'subnet-30': require('./bittensor/subnet-30.png'),
  'subnet-31': require('./bittensor/subnet-31.png'),
  'subnet-32': require('./bittensor/subnet-32.png'),
  'subnet-33': require('./bittensor/subnet-33.png'),
  'subnet-34': require('./bittensor/subnet-34.png'),
  'subnet-35': require('./bittensor/subnet-35.png'),
  'subnet-36': require('./bittensor/subnet-36.png'),
  'subnet-37': require('./bittensor/subnet-37.png'),
  'subnet-38': require('./bittensor/subnet-38.png'),
  'subnet-39': require('./bittensor/subnet-39.png'),
  'subnet-40': require('./bittensor/subnet-40.png'),
  'subnet-41': require('./bittensor/subnet-41.png'),
  'subnet-42': require('./bittensor/subnet-42.png'),
  'subnet-43': require('./bittensor/subnet-43.png'),
  'subnet-44': require('./bittensor/subnet-44.png'),
  'subnet-45': require('./bittensor/subnet-45.png'),
  'subnet-46': require('./bittensor/subnet-46.png'),
  'subnet-47': require('./bittensor/subnet-47.png'),
  'subnet-48': require('./bittensor/subnet-48.png'),
  'subnet-49': require('./bittensor/subnet-49.png'),
  'subnet-50': require('./bittensor/subnet-50.png'),
  'subnet-51': require('./bittensor/subnet-51.png'),
  'subnet-52': require('./bittensor/subnet-52.png'),
  'subnet-53': require('./bittensor/subnet-53.png'),
  'subnet-54': require('./bittensor/subnet-54.png'),
  'subnet-55': require('./bittensor/subnet-55.png'),
  'subnet-56': require('./bittensor/subnet-56.png'),
  'subnet-57': require('./bittensor/subnet-57.png'),
  'subnet-58': require('./bittensor/subnet-58.png'),
  'subnet-59': require('./bittensor/subnet-59.png'),
  'subnet-60': require('./bittensor/subnet-60.png'),
  'subnet-61': require('./bittensor/subnet-61.png'),
  'subnet-62': require('./bittensor/subnet-62.png'),
  'subnet-63': require('./bittensor/subnet-63.png'),
  'subnet-64': require('./bittensor/subnet-64.png'),
  'subnet-65': require('./bittensor/subnet-65.png'),
  'subnet-66': require('./bittensor/subnet-66.png'),
  'subnet-67': require('./bittensor/subnet-67.png'),
  'subnet-68': require('./bittensor/subnet-68.png'),
  'subnet-69': require('./bittensor/subnet-69.png'),
  'subnet-70': require('./bittensor/subnet-70.png'),
  'subnet-71': require('./bittensor/subnet-71.png'),
  'subnet-72': require('./bittensor/subnet-72.png'),
  'subnet-73': require('./bittensor/subnet-73.png'),
  'subnet-74': require('./bittensor/subnet-74.png'),
  'subnet-75': require('./bittensor/subnet-75.png'),
  'subnet-76': require('./bittensor/subnet-76.png'),
  'subnet-77': require('./bittensor/subnet-77.png'),
  'subnet-78': require('./bittensor/subnet-78.png'),
  'subnet-79': require('./bittensor/subnet-79.png'),
  'subnet-80': require('./bittensor/subnet-80.png'),
  'subnet-81': require('./bittensor/subnet-81.png'),
  'subnet-82': require('./bittensor/subnet-82.png'),
  'subnet-83': require('./bittensor/subnet-83.png'),
  'subnet-84': require('./bittensor/subnet-84.png'),
  'subnet-85': require('./bittensor/subnet-85.png'),
  en: EnglishLogo,
  vi: VietnameseLogo,
  chi: ChineseLogo,
  fr: FranchiseLogo,
  ja: JapaneseLogo,
  ru: RussianLogo,
  XLogo: XLogo,
  RestartLogo: RestartLogo,
};
