name: Build Dev
on:
  pull_request_review: {}
  pull_request: {}
  push:
    branches:
      - test-github-action

jobs:
  build-dev-android:
    strategy:
      matrix:
        step: ['android', 'ios', 'testflight']
    name: ${{ matrix.step }}
    runs-on: mac-worker
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: ${{ matrix.step }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        KS_PASSWORD: ${{ secrets.KS_PASSWORD }}
        NEXTCLOUD_CONFIG: ${{ secrets.NEXTCLOUD_CONFIG }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        REF_NAME: ${{ github.ref_name }}
        GITHUB_EVENT: ${{ toJson(github.event) }}
      run: |
        echo $GITHUB_EVENT
